FROM node:13-alpine As build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable AS prod-stage
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;"]