version: "3.9"
services:
    webapp-client:
        container_name: webapp-client
        environment:
            - REACT_APP_STORAGE=http://localhost:9000
        build: ./webapp-client
        volumes: 
            - ./webapp-client:/app
        ports: 
            - 3000:3000
    management-api:
        container_name: management-api
        build: ./management-api
        environment:
            - SANIC_NO_UJSON=true
            - SANIC_NO_UVLOOP=true
        volumes: 
            - ./management-api/src:/usr/src/app
        ports: 
            - 8000:8000
    minio:
        container_name: minio
        image: minio/minio
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minioadmin
        volumes:
            - ./storage:/data
        ports:
            - "9000:9000"
        command: server /data
    postgres-db:
        container_name: postgres-db
        build: ./postgres-db
        environment:
            - POSTGRES_PASSWORD=ccom
            - POSTGRES_DB=ccom
            - BITNAMI_DEBUG=true
        ports:
            - "5432:5432"
    jenkins:
        image: jenkins/jenkins:lts-jdk11
        ports:
            - 8080:8080
        volumes:
            - jenkins_home:/var/jenkins_home

volumes:
    jenkins_home:
  